# Generated by Django 3.0.7 on 2020-08-31 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_user_registration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=300)),
                ('description_cat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('date_field', models.DateTimeField()),
                ('video_upload', models.FileField(upload_to='videos')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.Category')),
            ],
        ),
    ]
